// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-projects.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "Listar projetos",
  description: "Lista os projetos (ebooks) acess\xEDveis do usu\xE1rio autenticado, com status de processamento e total de p\xE1ginas.",
  inputSchema: {
    limit: z.number().int().optional().describe("N\xFAmero m\xE1ximo de projetos a retornar (padr\xE3o 20)."),
    search: z.string().optional().describe("Filtro opcional por trecho do nome do projeto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("N\xE3o autenticado.");
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("projects").select("id, name, book_title, book_type, processing_status, total_pages, created_at, updated_at").order("updated_at", { ascending: false }).limit(take);
    if (search?.trim()) query = query.ilike("name", `%${search.trim()}%`);
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Detalhes do projeto",
  description: "Retorna os detalhes de um projeto, incluindo configura\xE7\xF5es globais de narra\xE7\xE3o e cap\xEDtulos.",
  inputSchema: { project_id: z2.string().describe("ID (uuid) do projeto.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    const [{ data: project, error }, { data: chapters }] = await Promise.all([
      supabase.from("projects").select("*").eq("id", project_id).maybeSingle(),
      supabase.from("chapters").select("id, title, start_page, end_page, order, videobook_status").eq("project_id", project_id).order("order")
    ]);
    if (error) throw new ToolError2(error.message);
    if (!project) throw new ToolError2("Projeto n\xE3o encontrado ou sem acesso.");
    const result = { project, chapters: chapters ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-pages.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_pages_default = defineTool3({
  name: "list_pages",
  title: "Listar p\xE1ginas",
  description: "Lista as p\xE1ginas de um projeto com o status de audiobook, audiodescri\xE7\xE3o e videobook.",
  inputSchema: {
    project_id: z3.string().describe("ID (uuid) do projeto."),
    from_page: z3.number().int().optional().describe("N\xFAmero da primeira p\xE1gina do intervalo."),
    to_page: z3.number().int().optional().describe("N\xFAmero da \xFAltima p\xE1gina do intervalo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, from_page, to_page }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("N\xE3o autenticado.");
    let query = supabaseForUser(ctx).from("pages").select("id, page_number, audiobook_status, audiodesc_status, video_status, audiodesc_validated, audiodesc_validation_score").eq("project_id", project_id).order("page_number");
    if (typeof from_page === "number") query = query.gte("page_number", from_page);
    if (typeof to_page === "number") query = query.lte("page_number", to_page);
    const { data, error } = await query;
    if (error) throw new ToolError3(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { pages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-page.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var get_page_default = defineTool4({
  name: "get_page",
  title: "Ler p\xE1gina",
  description: "Retorna o texto do audiobook e da audiodescri\xE7\xE3o de uma p\xE1gina espec\xEDfica de um projeto.",
  inputSchema: {
    project_id: z4.string().describe("ID (uuid) do projeto."),
    page_number: z4.number().int().describe("N\xFAmero da p\xE1gina dentro do projeto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, page_number }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("N\xE3o autenticado.");
    const { data, error } = await supabaseForUser(ctx).from("pages").select("id, page_number, audiobook_text, audiobook_style, audiobook_status, audiodesc_text, audiodesc_style, audiodesc_status, audiodesc_validated, audiodesc_validation_score, audiodesc_validation_violations").eq("project_id", project_id).eq("page_number", page_number).maybeSingle();
    if (error) throw new ToolError4(error.message);
    if (!data) throw new ToolError4("P\xE1gina n\xE3o encontrada ou sem acesso.");
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { page: data }
    };
  }
});

// src/lib/mcp/tools/update-page-text.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var update_page_text_default = defineTool5({
  name: "update_page_text",
  title: "Atualizar texto da p\xE1gina",
  description: "Atualiza o texto de narra\xE7\xE3o (audiobook) e/ou de audiodescri\xE7\xE3o de uma p\xE1gina do projeto.",
  inputSchema: {
    project_id: z5.string().describe("ID (uuid) do projeto."),
    page_number: z5.number().int().describe("N\xFAmero da p\xE1gina dentro do projeto."),
    audiobook_text: z5.string().optional().describe("Novo texto de narra\xE7\xE3o do audiobook."),
    audiodesc_text: z5.string().optional().describe("Novo texto de audiodescri\xE7\xE3o.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, page_number, audiobook_text, audiodesc_text }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("N\xE3o autenticado.");
    if (audiobook_text === void 0 && audiodesc_text === void 0) {
      throw new ToolError5("Informe audiobook_text e/ou audiodesc_text.");
    }
    const supabase = supabaseForUser(ctx);
    const { data: page, error: findError } = await supabase.from("pages").select("id").eq("project_id", project_id).eq("page_number", page_number).maybeSingle();
    if (findError) throw new ToolError5(findError.message);
    if (!page) throw new ToolError5("P\xE1gina n\xE3o encontrada ou sem acesso.");
    const patch = {};
    if (audiobook_text !== void 0) patch.audiobook_text = audiobook_text;
    if (audiodesc_text !== void 0) patch.audiodesc_text = audiodesc_text;
    const { data, error } = await supabase.from("pages").update(patch).eq("id", page.id).select("id, page_number, audiobook_text, audiodesc_text").maybeSingle();
    if (error) throw new ToolError5(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { page: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rlsipiinlgjytlmrqbav";
var mcp_default = defineMcp({
  name: "accessibility-studio",
  title: "Accessibility Studio",
  version: "0.1.0",
  instructions: "Ferramentas do Accessibility Studio (audiobooks, audiodescri\xE7\xE3o e videobooks acess\xEDveis). Use `list_projects` para encontrar projetos, `get_project` para detalhes e cap\xEDtulos, `list_pages` e `get_page` para ler textos de narra\xE7\xE3o e audiodescri\xE7\xE3o, e `update_page_text` para editar esses textos. Todas as opera\xE7\xF5es s\xE3o feitas como o usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, get_project_default, list_pages_default, get_page_default, update_page_text_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
